%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/jaywellik/Dropbox/Indonesia2016_Raung/Jay_Analog_Query_Output_Coords.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/02/04 14:22:32

%% Initialize variables.
% textfile = 'Jay_Analog_Query_Output_Coords.txt';
filename = ['/Users/jaywellik/Dropbox/Indonesia2016_Raung/' textfile];
delimiter = '\t';

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,10,14,15,16,17,18,19,20,21,23,24,25]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,10,14,15,16,17,18,19,20,21,23,24,25]);
rawCellColumns = raw(:, [1,4,5,6,7,8,9,11,12,13,22,26]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
VolcanoName = rawCellColumns(:, 1);
Activity_ID = cell2mat(rawNumericColumns(:, 1));
VolcanoNumber = cell2mat(rawNumericColumns(:, 2));
MorphType1 = rawCellColumns(:, 2);
MorphType2 = rawCellColumns(:, 3);
MorphType3 = rawCellColumns(:, 4);
MorphType4 = rawCellColumns(:, 5);
MorphType5 = rawCellColumns(:, 6);
MorphType6 = rawCellColumns(:, 7);
TectonicSetting = cell2mat(rawNumericColumns(:, 3));
RockType = rawCellColumns(:, 8);
Country = rawCellColumns(:, 9);
ActivityType = rawCellColumns(:, 10);
StartDateYear = cell2mat(rawNumericColumns(:, 4));
StartDateMonth = cell2mat(rawNumericColumns(:, 5));
StartDateDay = cell2mat(rawNumericColumns(:, 6));
EndDateYear = cell2mat(rawNumericColumns(:, 7));
EndDateMonth = cell2mat(rawNumericColumns(:, 8));
EndDateDay = cell2mat(rawNumericColumns(:, 9));
DurationYears = cell2mat(rawNumericColumns(:, 10));
ExplosivityIndexMax = cell2mat(rawNumericColumns(:, 11));
ExplosivityIndexModifier = rawCellColumns(:, 11);
LatitudeDecimal = cell2mat(rawNumericColumns(:, 12));
LongitudeDecimal = cell2mat(rawNumericColumns(:, 13));
Elevation = cell2mat(rawNumericColumns(:, 14));
Remarks = rawCellColumns(:, 12);


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;