%% Import Unzen data from Wendy's text files.
% Script for importing data from the following text file:
%
%    /Users/jwellik/Documents/JAY-VDAP/unzenpapers-fromWendy/1985.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/10/19 10:52:14

%% Initialize variables.
directory = '/Users/jwellik/Documents/JAY-VDAP/unzenpapers-fromWendy/';
% year = [1995];
year = 1985:1997;


yyyy = [];
mm = [];
dd = [];
HH = [];
MM = [];
SS = [];
lat = [];
lon = [];
depth = [];
mag = [];


for n = 1:length(year)
    
    
    filename = [directory num2str(year(n)) '.txt'];
    
    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: double (%f)
    %   column7: double (%f)
    %	column8: double (%f)
    %   column9: double (%f)
    %	column10: double (%f)
    %   column11: double (%f)
    %	column12: double (%f)
    %   column13: double (%f)
    %	column14: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%4f%3f%3f%3f%3f%8f%9f%10f%8f%5f%7f%7f%7f%f%[^\n\r]';
    
    %% Open the text file.
    fileID = fopen(filename,'r');
    
    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '',  'ReturnOnError', false);
    
    %% Close the text file.
    fclose(fileID);
    
    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.
    
    %% Allocate imported array to column variable names
    yyyy = [yyyy; dataArray{:, 1}];
    mm = [mm; dataArray{:, 2}];
    dd = [dd; dataArray{:, 3}];
    HH = [HH; dataArray{:, 4}];
    MM = [MM; dataArray{:, 5}];
    SS = [SS; dataArray{:, 6}];
    lat = [lat; dataArray{:, 7}];
    lon = [lon; dataArray{:, 8}];
    depth = [depth; dataArray{:, 9}];
    mag = [mag; dataArray{:, 10}];
    
    
    t = datestr([yyyy mm dd HH MM SS]);
    
    
end


T = table(t,lat,lon,depth,mag,'VariableNames',{'DateTime' 'Latitude' 'Longitude' 'Depth' 'Location'})
catalog = table2struct(T);


%% Clear temporary variable

% save([directory 'unzenCatalogFromWendy.mat'],'catalog');
% 
% clearvars -except catalog
