function [chronology] = importRaungActivityChronology(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DATESTR,DESCRIPTION] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [DATESTR,DESCRIPTION] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [DateStr,Description] = importfile('RaungActivityChronology.txt',3, 8);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/04/01 13:46:21

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));


%% Split data into numeric and cell columns.
rawNumericColumns = {};
rawCellColumns = raw(:, [1,2]);


%% Allocate imported array to column variable names
dates = rawCellColumns(:, 1);
datesdt = datetime(dates,'InputFormat','uuuu/MM/dd''T''HH:mm:SSXXX','TimeZone','UTC');
chronology.datesdn = datenum(datestr(datesdt));
chronology.description = rawCellColumns(:, 2);


