%% defineBBasic

BBasic = Budget('Basic Budget', '2016-10-01', 12);

BBasic = addGroup( BBasic, 'Taxes', -60000*0.33, ...
    {'State Tax', 'Federal Tax', 'Gov Fine', 'Misc. Deduction', ...
    'State Tax Refund', 'Federal Tax Refund'});
BBasic = addGroup( BBasic, 'Housing', -(750*12), ...
    {'Mortgage & Rent', 'Utilities', 'Internet', ...
    'Trash Service', 'Water'});
BBasic = addGroup( BBasic, 'Other', -60000*0.27, ...
    {'Restaurants', 'Coffee Shops', 'Alcohol & Bars', ...
    'Groceries', 'Home Supplies', 'Pharmacy', ...
    'Gas & Fuel', 'Parking', 'Public Transportation', 'Public Rail', ...
    'Movies & DVDs', 'Books', 'Music', 'Arts', ...
    'Electronics & Software', 'Mobile Phone', ...
    'Amusement', 'Park Fees & Camping', 'Sporting Events', ...
    'Education', 'Charity', 'Shipping', ...
    'Misc Items', 'Gift', 'Sports', 'Vacation', ...
    'Gym', ...
    'Shopping', 'Sporting Goods', 'Clothing', ...
    'Bike Service Parts', 'Home', 'Furnishings', ...
    'Auto Insurance', 'Service & Parts', 'Car Fees', ...
    'Air Travel', 'Rental Car & Taxi', 'Travel'});
BBasic = addGroup( BBasic, 'Salary', 60000, {'Paycheck', 'Salary'});
BBasic = addGroup( BBasic, 'Other Income', 0, {'Income', 'Interest Income', 'Gift Received'});
BBasic = addGroup( BBasic, 'Per Diem', 0, {'Per Diem'});
BBasic = addGroup( BBasic, 'Savings', 0, {'TSP'});
BBasic = addGroup( BBasic, 'Benefits', 60000*0.0395, {'TSP Matched'});