%% defineB503020

B503020 = Budget('Fifty-Thirty-Twenty (50-30-20)', '2016-10-01', 12);    
    
B503020 = addGroup(B503020, 'Necessities', -60000*0.50, ...
    {'State Tax', 'Federal Tax', 'Gov Fine', 'Misc. Deduction', ...
    'State Tax Refund', 'Federal Tax Refund', ...
    'Mortgage & Rent', 'Utilities', 'Internet', ...
    'Trash Service', 'Water', ...
    'Retirement - FERS/FRAE', 'Medicare', 'OASDI Tax', ...
    'FEGLI - Regular', ...
    'Health Benefits', 'TSP Savings'});
B503020 = addGroup(B503020, 'Personal', -60000*0.30, ...
    {'Restaurants', 'Coffee Shops', 'Alcohol & Bars', ...
    'Groceries', 'Home Supplies', 'Pharmacy', ...
    'Gas & Fuel', 'Parking', 'Public Transportation', 'Public Rail', ...
    'Movies & DVDs', 'Books', 'Music', 'Arts', ...
    'Electronics & Software', 'Mobile Phone', ...
    'Amusement', 'Park Fees & Camping', 'Sporting Events', ...
    'Education', 'Charity', 'Shipping', ...
    'Misc Items', 'Gift', 'Sports', 'Vacation', ...
    'Gym', ...
    'Shopping', 'Sporting Goods', 'Clothing', ...
    'Bike Service Parts', 'Home', 'Furnishings', ...
    'Auto Insurance', 'Service & Parts', 'Car Fees', ...
    'Air Travel', 'Rental Car & Taxi', 'Travel'});
B503020 = addGroup(B503020, 'Salary', 60000, {'Paycheck', 'Salary'});
B503020 = addGroup(B503020, 'Other Income', 0, {'Income', ...
    'Interest Income', 'Gift Received'});
B503020 = addGroup(B503020, 'Per Diem', 0000, {'Per Diem'});
B503020 = addGroup(B503020, 'Savings', 0, {'TSP'});
B503020 = addGroup(B503020, 'Benefits', 60000*0.0395, {'TSP Matched'});

